version: '2'

services: 
    web:
        hostname: ark-web1
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./files/etc/nginx/sites-available/:/etc/nginx/sites-available/
        networks: 
            - web-network-01
    php:
        hostname: ark-php1
        image: pterodactyl-standalone
        volumes:
            - ./files/srv/web:/srv/web
        environment:
            - "db_host=ark-pterodb"
            - "db_port=3306"
            - "db_name=pterodb"
            - "db_user=ptero"
            - "db_pass=pterodbpassword"
            - "panel_url="
            - "timezone="
            - "email_driver="
            - "panel_email="
            - "email_user="
            - "email_pass="
            - "email_domain="
            - "email_port="
            - "admin_email="
            - "admin_pass="
            - "admin_stat=1"
        networks: 
            - web-network-01
    db:
        hostname: ark-db1
        image: mariadb:latest
        command: mysqld
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=pterodb
            - MYSQL_ROOT_PASSWORD=pterosqlpassword
            - MYSQL_PASSWORD=pterodbpassword
            - MYSQL_USER=ptero
        networks: 
            - web-network-01

networks: 
    web-network-01:
        driver: bridge
