version: '2'

services: 
    web:
        container_name: web1
        hostname: ark-web1
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            # The below location doesn't exist. Why? Because ./files is referring to the host, but additionally we never copied any files up for nginx.
            - ./files/etc/nginx/sites-available/pterodactyl.conf:/etc/nginx/sites-available/pterodactyl.conf
            # The below is a workaround for adding the symlink for sites-enabled.
            - ./files/etc/nginx/sites-enabled/pterodactyl.conf:/etc/nginx/sites-enabled/pterodactyl.conf
            - sharedvolumeXX53:/var/www/pterodactyl/html/public/
        networks:
            - web-network-01
    php:
        depends_on:
            - "sql"
        container_name: php1
        hostname: ark-php1
        image: quay.io/xyelz/docker-pterodactyl
        volumes:
            - sharedvolumeXX53:/apps/pterodactyl/
            #- ./files/etc/supervisor/conf.d/pterodactyl-worker.conf:/etc/supervisor/conf.d/pterodactyl-worker.conf
        environment:
            - db_host=ark-sql1
            - db_port=3306
            - db_name=pterodb
            - db_user=ptero
            - db_pass=pterodbpassword
            - panel_url=
            - timezone=
            - email_driver=
            - panel_email=
            - email_user=
            - email_pass=
            - email_domain=
            - email_port=
            - admin_email=
            - admin_pass=
            - admin_stat=1
        networks: 
            - web-network-01
    sql:
        container_name: sql1
        hostname: ark-sql1
        image: mariadb:latest
        command: mysqld
        volumes:
            # Should we change the below volume location?
            - ./dbdata:/var/lib/mysql/
        environment:
            - MYSQL_DATABASE=pterodb
            - MYSQL_ROOT_PASSWORD=pterosqlpassword
            - MYSQL_PASSWORD=pterodbpassword
            - MYSQL_USER=ptero
        networks:
            - web-network-01
volumes:
    sharedvolumeXX53:
networks:
    web-network-01:
        driver: bridge
