version: '2'

services: 
    web:
        hostname: ark-web1
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./files/etc/nginx/sites-available/pterodactyl.conf/:/etc/nginx/sites-available/pterodactyl.conf/
        networks:
            - web-network-01
    php:
        depends_on:
            - "db"
        hostname: ark-php1
        image: quay.io/repository/xyelz/pterodactyl-php
        volumes:
            - ./files/etc/supervisor/conf.d/pterodactyl-worker.conf/:/etc/supervisor/conf.d/pterodactyl-worker.conf/
#           - ./files/srv/web:/srv/web
        environment:
            - "db_host=ark-pterodb"
            - "db_port=3306"
            - "db_name=pterodb"
            - "db_user=ptero"
            - "db_pass=pterodbpassword"
            - "panel_url="
            - "timezone="
            - "email_driver="
            - "panel_email="
            - "email_user="
            - "email_pass="
            - "email_domain="
            - "email_port="
            - "admin_email="
            - "admin_pass="
            - "admin_stat=1"
            - "php artisan pterodactyl:env"
            - "php artisan pterodactyl:mail"
            - "php artisan migrate"
            - "php artisan db:seed"
            - "php artisan pterodactyl:user"
        networks: 
            - web-network-01
    db:
        hostname: ark-sql1
        image: mariadb:latest
        command: mysqld
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=pterodb
            - MYSQL_ROOT_PASSWORD=pterosqlpassword
            - MYSQL_PASSWORD=pterodbpassword
            - MYSQL_USER=ptero
        networks:
            - web-network-01

networks:
    web-network-01:
        driver: bridge
